bump to v1.9.6
ava-labs/avalanche-network-runner pull request #388
Opened 2023-01-05 00:40 UTC by darioush

Bumps avalanchego to v1.9.6

2023-01-05 19:13 UTC, holisticode approved these changes

2023-01-06 16:26 UTC, felipemadero requested changes
Can you bump E2E version also?

2023-01-06 16:32 UTC, felipemadero reviewed
Can you PR to https://github.com/ava-labs/avalanche-network-runner/pull/386 ? will change that PR name and associated issue accordingly

2023-01-06 17:17 UTC, darioush commented
moved the necessary changes to https://github.com/ava-labs/avalanche-network-runner/pull/386

2023-01-06 17:17 UTC, closed without merging